[tool.uv.sources]
ommx = { workspace = true }

[tool.uv.workspace]
members = ["python/ommx*"]

[dependency-groups]
dev = [
  "ipython>=8.18.1",
  "jupyter-book>=1.0.3",
  "jupyter>=1.1.1",
  "jupyterlab>=4.3.5",
  "markdown-code-runner>=2.1.0",
  "matplotlib>=3.10.7",
  "mypy-protobuf>=3.6.0",
  "nbqa>=1.9.1",
  "nbval>=0.11.0",
  "networkx>=3.2.1",
  "pluggy",
  "pyright>=1.1.394",
  "pytest-codspeed>=3.2.0",
  "pytest-github-actions-annotate-failures",
  "pytest>=8.3.4",
  "pyyaml>=6.0.3",
  "ruamel-yaml>=0.18.10",
  "ruff>=0.9.6",
  "tomlkit>=0.13.2",
]
