[project]
name = "ommx"
version = "0.0.1"
description = "Open Mathematical prograMming eXchange (OMMX)"
authors = [
    { name="Jij Inc.", email="info@j-ij.com" },
]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "protobuf>=5.26.1, <6.0.0",
]


[project.optional-dependencies]
dev = [
    "mypy>=0.910",
    "mypy-protobuf",
    "pyright",
    "pytest",
    "types-protobuf>=0.1.14",
]


[project.urls]
Homepage = "https://github.com/Jij-Inc/ommx"
Issues = "https://github.com/Jij-Inc/ommx/issues"


[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
